// C.E.E. Based Model Examination [TEST - XXXVII (SET-B)]
// Physics (1-50) and Chemistry (51-100)
const questions = [
  // ---------------- PHYSICS ----------------
  { subject: "Physics", question: "The dimensions of self-inductance are:", options: ["[MLT⁻²A⁻¹]", "[ML²T⁻¹A⁻²]", "[ML²T⁻²A⁻²]", "[ML²T⁻²A⁻¹]"], answer: 2 },
  { subject: "Physics", question: "A player kicks a ball at an angle θ with horizontal. The maximum horizontal range corresponds to an angle of", options: ["30° with horizontal", "45° with horizontal", "60° with horizontal", "75° with horizontal"], answer: 1 },
  { subject: "Physics", question: "A balloon is moving upward with velocity 10 m/s. It releases a stone which comes down to the ground in 5 sec. The height of the balloon from the ground at the moment when the stone was dropped is:", options: ["40m", "49m", "75m", "100m"], answer: 2 },
  { subject: "Physics", question: "A person holds a box weighing 60N on his hand for 5 minutes. The amount of work done by him is:", options: ["Zero", "200N", "600N", "900N"], answer: 0 },
  { subject: "Physics", question: "Given A⃗ + B⃗ = C⃗ and A + B = C (magnitudes), then the angle between A⃗ and B⃗ is", options: ["0", "π/4", "π/2", "π"], answer: 0 },
  { subject: "Physics", question: "If the KE of a body becomes four times its initial value, the new momentum will:", options: ["Become twice its initial value", "Become thrice its initial value", "Become four times its initial value", "Remain constant"], answer: 0 },
  { subject: "Physics", question: "A parrot sitting on the floor of a wire cage which is being carried by a person, starts flying. The person will feel that the cage is now:", options: ["Heavier", "Lighter", "Same in weight", "Lighter in beginning and heavier later"], answer: 2 },
  { subject: "Physics", question: "Two springs each of force constant K are connected end to end (in series); the force constant of the combination will be:", options: ["K", "K/2", "2K", "Zero"], answer: 1 },
  { subject: "Physics", question: "Gravitational force between two bodies is independent of:", options: ["Mass of the bodies", "Separation between their centers", "Medium between the bodies", "None of the above"], answer: 2 },
  { subject: "Physics", question: "As a car moves at constant speed on a convex bridge from one end to the other, the thrust of the car on the bridge:", options: ["Remains unchanged", "Decreases gradually", "First decreases then increases", "First increases then decreases"], answer: 2 },
  { subject: "Physics", question: "The pressure of a gas filled in the bulb of a constant volume gas thermometer at 0°C and 100°C are 28.6 cm and 36.6 cm of mercury respectively. The temperature of the bulb at which the pressure will be 35.0 cm of mercury is:", options: ["80°C", "70°C", "55°C", "40°C"], answer: 0 },
  { subject: "Physics", question: "When a capillary tube is dipped in a liquid, the capillary rise is h₁. When the inner surface is coated with wax, the capillary rise is h₂, then:", options: ["h₁ = h₂", "h₁ < h₂", "h₁ > h₂", "a and b both"], answer: 2 },
  { subject: "Physics", question: "Water is used as coolant because:", options: ["Of its high specific heat capacity", "It is easily available", "Of its low boiling point", "It is of higher density"], answer: 0 },
  { subject: "Physics", question: "A gas is allowed to expand isothermally. The root mean square velocity of the molecules:", options: ["Will increase", "Will decrease", "Will remain unchanged", "Depends on other factors"], answer: 2 },
  { subject: "Physics", question: "300g of water at 25°C and 100g of ice at 0°C were mixed. What will be the final temperature of the mixture?", options: ["25°C", "10°C", "15°C", "0°C"], answer: 3 },
  { subject: "Physics", question: "What is the temperature on the Fahrenheit scale corresponding to 4°C?", options: ["37°F", "38°F", "39.2°F", "41.3°F"], answer: 2 },
  { subject: "Physics", question: "In diffraction from a single slit, the angular width of the central maxima does not depend on:", options: ["Wavelength of light used", "Width of slit", "Distance of slit from screen", "Ratio of wavelength and slit width"], answer: 2 },
  { subject: "Physics", question: "What changes on polarization of light?", options: ["Intensity", "Phase", "Wavelength", "All"], answer: 0 },
  { subject: "Physics", question: "The angle of a prism is A and that of minimum deviation is (180° − 2A). Then the refractive index of the material is:", options: ["sin(A/2)", "cos(A/2)", "tan(A/2)", "cot(A/2)"], answer: 3 },
  { subject: "Physics", question: "Total internal reflection of light is possible if light travels from:", options: ["Air to glass", "Vacuum to air", "Air to water", "Water to air"], answer: 3 },
  { subject: "Physics", question: "An object is placed at the focus of a concave lens of focal length f. The image is then formed at a distance:", options: ["∞", "f", "f/2", "2f"], answer: 2 },
  { subject: "Physics", question: "Two mirrors are kept at 60° to each other and a body is placed at the middle. The total number of images formed is:", options: ["6", "8", "5", "3"], answer: 2 },
  { subject: "Physics", question: "The magnetic field due to a long solenoid carrying current I is proportional to:", options: ["I", "I³", "√I", "I⁻¹"], answer: 0 },
  { subject: "Physics", question: "At a certain place, the horizontal component of earth's magnetic field is √3 times its vertical component. The angle of dip at this place is:", options: ["0", "π/4", "π/6", "π/3"], answer: 2 },
  { subject: "Physics", question: "An isolated conducting sphere is given a positive charge. Its mass:", options: ["Gets increased", "Gets decreased", "Remains the same", "Mass is not involved during electrification"], answer: 1 },
  { subject: "Physics", question: "The peak voltage in a 220V AC supply is nearly:", options: ["220V", "253V", "311V", "444V"], answer: 2 },
  { subject: "Physics", question: "A galvanometer of resistance 20Ω shows a deflection of 10 divisions when a current of 1mA is passed through it. If a shunt of 4Ω is connected and there are 50 divisions on the scale, the range of the galvanometer is:", options: ["1A", "3A", "10A", "30mA"], answer: 3 },
  { subject: "Physics", question: "The capacitance of a parallel plate capacitor does not depend upon:", options: ["Area of the plates", "Medium between the plates", "Distance between the plates", "Metal of the plates"], answer: 3 },
  { subject: "Physics", question: "The current carrying wire is:", options: ["Negatively charged", "Positively charged", "Neutral", "Sometimes positively and sometimes negatively charged"], answer: 2 },
  { subject: "Physics", question: "The resistance of a wire of uniform diameter 'd' and length 'l' is R. The resistance of another wire of the same material but diameter 2d and length 4l will be:", options: ["2R", "R", "R/2", "R/4"], answer: 1 },
  { subject: "Physics", question: "One requires an energy Eₙ to remove a nucleon from a nucleus and an energy Eₑ to remove an electron from an atom. Then:", options: ["Eₙ = Eₑ", "Eₙ < Eₑ", "Eₙ > Eₑ", "Eₙ ≥ Eₑ"], answer: 2 },
  { subject: "Physics", question: "A closed organ pipe and an open organ pipe have their first overtones identical in frequency. Their lengths are in the ratio:", options: ["1:2", "2:3", "3:4", "4:5"], answer: 2 },
  { subject: "Physics", question: "An open organ pipe vibrates in its fundamental mode. The pressure vibration is maximum at:", options: ["The upper end", "The lower end", "The middle of the pipe", "Distance 2/3 from the upper end"], answer: 2 },
  { subject: "Physics", question: "A long solenoid has radius A and number of turns per unit length n. If it carries a current I, then the magnetic field on its axis is directly proportional to:", options: ["4IR", "nI", "(nI)/R", "n²I"], answer: 1 },
  { subject: "Physics", question: "A charge Q is placed at the corner of a cube. The electric flux through all six faces of the cube is:", options: ["Q/3ε₀", "Q/6ε₀", "Q/8ε₀", "Qε₀"], answer: 2 },
  { subject: "Physics", question: "The phase difference between V and I of an LCR circuit in series resonance is:", options: ["π", "π/2", "0", "π/3"], answer: 2 },
  { subject: "Physics", question: "In a resonance column, the first and second resonances are obtained at depths 22.7 cm and 70.2 cm. The third resonance will be obtained at:", options: ["117.7 cm", "92.9 cm", "115.5 cm", "112.5 cm"], answer: 0 },
  { subject: "Physics", question: "The specific charge for positive rays is much less than the specific charge for cathode rays. This is because:", options: ["Positive rays are positively charged", "Charge on positive rays is less", "Positive rays are comprised of ionized atoms", "Experimental method for determination is wrong"], answer: 2 },
  { subject: "Physics", question: "An electron of mass m and charge e is accelerated from rest through a potential difference of V volts in vacuum. The speed of the electron will be:", options: ["√(eV/m)", "√(2eV/m)", "√(2eV)/m", "√(4eV/m)"], answer: 1 },
  { subject: "Physics", question: "The work function of a substance is 1.6 eV. The longest wavelength of light that can produce photoemission from the substance is:", options: ["2900 Å", "3867 Å", "5800 Å", "7734 Å"], answer: 3 },
  { subject: "Physics", question: "For the Balmer series that lies in the visible region, the shortest wavelength corresponds to quantum number:", options: ["n = 1", "n = 3", "n = 4", "n = ∞"], answer: 3 },
  { subject: "Physics", question: "An electric field can deflect:", options: ["X-rays", "Neutrons", "α-rays", "γ-rays"], answer: 2 },
  { subject: "Physics", question: "The de Broglie wavelength of an electron in the first orbit of Bohr's hydrogen atom is equal to:", options: ["Radius of the orbit", "Diameter of the orbit", "Perimeter of the orbit", "Half of the perimeter of the orbit"], answer: 2 },
  { subject: "Physics", question: "An X-ray tube operates on 30KV. Calculate the minimum wavelength emitted:", options: ["0.133 Å", "1.2 Å", "0.4 Å", "6.6 Å"], answer: 2 },
  { subject: "Physics", question: "The radius R of a nucleus changes with the nucleon number A as:", options: ["R ∝ A²ᐟ³", "R ∝ A¹ᐟ³", "R ∝ A⁰", "R ∝ A"], answer: 1 },
  { subject: "Physics", question: "Zener diode is used for:", options: ["Rectification", "Stabilization", "Amplification", "All"], answer: 1 },
  { subject: "Physics", question: "If germanium is doped with a donor impurity, the donor atoms should be:", options: ["Tetravalent", "Pentavalent", "Trivalent", "None of these"], answer: 1 },
  { subject: "Physics", question: "In a P-type semiconductor, the valency of the impurity is:", options: ["1", "3", "4", "5"], answer: 1 },
  { subject: "Physics", question: "The galaxy to which our solar system belongs is called:", options: ["Milky Way", "Radio galaxy", "Solar galaxy", "Elliptical galaxy"], answer: 0 },
  { subject: "Physics", question: "Very small stars having diameter 1/50th that of the sun are called:", options: ["Dwarfs", "White dwarfs", "Milky Way", "Neutron stars"], answer: 1 },

  // ---------------- CHEMISTRY ----------------
  { subject: "Chemistry", question: "If NA is Avogadro's number, then the number of valence electrons in 4.2g of nitride ions (N³⁻) is:", options: ["2.4NA", "6.2NA", "1.6NA", "3.2NA"], answer: 0 },
  { subject: "Chemistry", question: "For the orthorhombic system, axial ratios are a≠b≠c and the axial angles are:", options: ["α = β = γ ≠ 90°", "α = β = γ = 90°", "α = γ = 90°, β ≠ 90°", "α ≠ β ≠ γ = 90°"], answer: 1 },
  { subject: "Chemistry", question: "If the atomic mass of oxygen were taken as 100, the molecular mass of water would be approximately:", options: ["5.25", "112.5", "102", "106.2"], answer: 1 },
  { subject: "Chemistry", question: "For which one of the following sets of four quantum numbers will an electron have the highest energy?", options: ["n=3, l=2, m=1, s=1/2", "n=4, l=2, m=-1, s=1/2", "n=4, l=1, m=0, s=-1/2", "n=5, l=0, m=0, s=-1/2"], answer: 1 },
  { subject: "Chemistry", question: "Which of the following carbonates decomposes at the highest temperature?", options: ["MgCO3", "CaCO3", "SrCO3", "BaCO3"], answer: 3 },
  { subject: "Chemistry", question: "Which compound has the maximum number of lone pairs of electrons on the central atom?", options: ["[ClO3]⁻", "XeF4", "SF4", "[I3]⁻"], answer: 3 },
  { subject: "Chemistry", question: "Oxidation number of chromium in K3CrO8 is:", options: ["+4", "+5", "+6", "+8"], answer: 1 },
  { subject: "Chemistry", question: "100 kg of iron ore (Fe2O3) containing 20% impurities, on reduction with CO gives iron equal to:", options: ["112 kg", "80 kg", "160 kg", "56 kg"], answer: 3 },
  { subject: "Chemistry", question: "Aqueous solution of acetic acid contains:", options: ["CH3COO⁻ and H⁺", "CH3COO⁻, H3O⁺ and CH3COOH", "CH3COO⁻, H3O⁺ and H⁺", "CH3COOH, CH3COO⁻ and H⁺"], answer: 1 },
  { subject: "Chemistry", question: "Which one of the following molecular hydrides acts as a Lewis acid?", options: ["NH3", "H2O", "B2H6", "CH4"], answer: 2 },
  { subject: "Chemistry", question: "A solution of 0.1N NH4OH and 0.1N NH4Cl has pH 9.25. Find the pKb of NH4OH:", options: ["9.25", "4.75", "3.75", "8.25"], answer: 1 },
  { subject: "Chemistry", question: "The mole fraction of solute in a one molal aqueous solution is:", options: ["0.009", "0.018", "0.027", "0.036"], answer: 1 },
  { subject: "Chemistry", question: "For an elementary reaction, the specific rate constants for the forward and reverse reactions are 0.50 and 5×10⁴ respectively. The equilibrium constant for the reaction would be:", options: ["2.5×10³", "2.5×10⁴", "1×10⁻⁵", "1×10⁵"], answer: 2 },
  { subject: "Chemistry", question: "In which of the following cases does the reaction go farthest to completion?", options: ["K = 10³", "K = 10²", "K = 10", "K = 1"], answer: 0 },
  { subject: "Chemistry", question: "A colloidal sol is:", options: ["A true solution", "A suspension", "A heterogeneous sol", "A homogeneous sol"], answer: 2 },
  { subject: "Chemistry", question: "At constant T, P, which of the following statements is correct for the reaction: CO(g) + 1/2 O2(g) → CO2(g)", options: ["ΔH = ΔE", "ΔH < ΔE", "ΔH > ΔE", "ΔH is independent"], answer: 1 },
  { subject: "Chemistry", question: "Hydrogen diffuses 6 times faster than gas X. The molecular mass of X will be:", options: ["72", "140", "144", "100"], answer: 0 },
  { subject: "Chemistry", question: "The normality of a 6% (W/V) solution of acetic acid is:", options: ["0.01N", "0.1N", "1N", "0.5N"], answer: 2 },
  { subject: "Chemistry", question: "The net energy change in a reversible cyclic process is:", options: ["3/2 RT", "Always > 0", "Always < 0", "0"], answer: 3 },
  { subject: "Chemistry", question: "Which physical property of dihydrogen is wrong?", options: ["Odourless gas", "Tasteless gas", "Colourless gas", "Non-inflammable gas"], answer: 3 },
  { subject: "Chemistry", question: "The gas ozone (O3) cannot oxidise:", options: ["KI", "FeSO4", "KMnO4", "K2MnO4"], answer: 2 },
  { subject: "Chemistry", question: "Carbon and silicon belong to group (IV). The maximum coordination number of carbon in commonly occurring compounds is 4, whereas that of silicon is 6. This is due to:", options: ["Large size of silicon", "More electropositive nature of silicon", "Availability of low lying d-orbital in silicon", "Both a and c"], answer: 2 },
  { subject: "Chemistry", question: "Which of the following oxides of nitrogen is neutral?", options: ["N2O5", "NO2", "N2O3", "N2O"], answer: 3 },
  { subject: "Chemistry", question: "Fullerene is commercially prepared by:", options: ["Fusing fluorine and chloride", "Burning graphite", "Passing a high voltage electric discharge through graphite electrodes", "Thermal decomposition of carbon"], answer: 2 },
  { subject: "Chemistry", question: "Which acid is not formed by the action of water on phosphorus pentoxide?", options: ["HPO3", "H4P2O7", "H3PO4", "H3PO3"], answer: 3 },
  { subject: "Chemistry", question: "SO2 is obtained when:", options: ["Oxygen reacts with dilute sulphuric acid", "Hydrolysis of dilute H2SO4", "Concentrated H2SO4 reacts with Na2SO3", "All of these"], answer: 2 },
  { subject: "Chemistry", question: "Anhydrous mixture of KF and HF contains which ions:", options: ["K⁺, HF2⁻", "(KF)⁺, (HF)⁻", "KH⁺, F⁻", "K⁺, H⁺, F⁻"], answer: 0 },
  { subject: "Chemistry", question: "The most volatile of all liquids is:", options: ["Ether", "Liquid He", "Liquid Nitrogen", "Liquid Neon"], answer: 1 },
  { subject: "Chemistry", question: "Thermal decomposition method is used to purify:", options: ["Ni", "Cr", "Sn", "Pb"], answer: 0 },
  { subject: "Chemistry", question: "Colloidal solution of graphite in water is called:", options: ["Oildag", "Aquadag", "Aquagraph", "Peat"], answer: 1 },
  { subject: "Chemistry", question: "Molecular formula of Glauber's salt is:", options: ["MgSO4.7H2O", "CuSO4.5H2O", "FeSO4.7H2O", "Na2SO4.10H2O"], answer: 3 },
  { subject: "Chemistry", question: "A tetrahedral complex has a coordination number of:", options: ["3", "6", "4", "8"], answer: 2 },
  { subject: "Chemistry", question: "Petroleum refining involves:", options: ["Vacuum distillation", "Fractional distillation", "Steam distillation", "Passing over activated charcoal"], answer: 1 },
  { subject: "Chemistry", question: "Which of the following compounds reacts fastest with Lucas reagent?", options: ["1-Butanol", "2-Butanol", "2-Methyl-2-propanol", "2-Methyl-1-propanol"], answer: 2 },
  { subject: "Chemistry", question: "The total number of stereoisomers of the compound CH3CHBrCHBrCOOH is:", options: ["0", "1", "3", "4"], answer: 3 },
  { subject: "Chemistry", question: "An unknown alcohol is treated with Lucas reagent to determine whether it is primary, secondary or tertiary. Which alcohol reacts fastest and by which mechanism?", options: ["2° alcohol by SN1", "3° alcohol by SN1", "2° alcohol by SN2", "3° alcohol by SN2"], answer: 1 },
  { subject: "Chemistry", question: "The oxidation of aniline by K2Cr2O7/H2SO4 mainly gives:", options: ["Nitrobenzene", "Benzoic acid", "p-Benzoquinone", "Benzamide"], answer: 2 },
  { subject: "Chemistry", question: "In the greenhouse effect, methane causes:", options: ["Absorption of heat", "Reflection of light", "Destruction of the greenhouse", "None"], answer: 0 },
  { subject: "Chemistry", question: "Cl2 reacts with CS2 in the presence of AlCl3 to form:", options: ["CHCl3", "CCl4", "Cl4", "CHI3"], answer: 1 },
  { subject: "Chemistry", question: "Glycerol reacts with Fenton's reagent to give:", options: ["Glyceric acid", "Meso oxalic acid", "Glycerose", "Tartonic acid"], answer: 0 },
  { subject: "Chemistry", question: "Phenol on distilling with zinc dust gives:", options: ["Toluene", "Benzene", "Zinc phenoxide", "Acetylene"], answer: 1 },
  { subject: "Chemistry", question: "Which compound gives Cannizzaro's reaction?", options: ["(CH3)3C-CO-C(CH3)3", "CH3CHO", "(CH3)2CH-CHO", "Both b and c"], answer: 0 },
  { subject: "Chemistry", question: "Ether on hydrolysis gives:", options: ["Carboxylic acid", "Alcohols", "Esters", "Ketones"], answer: 1 },
  { subject: "Chemistry", question: "Which of the following compounds gives the Claisen condensation reaction?", options: ["HCOOCH3", "CH3COOCH3", "PhCOOCH3", "Both a and c"], answer: 1 },
  { subject: "Chemistry", question: "Benzaldehyde is oxidised by:", options: ["Tollen's reagent", "Fehling's solution", "Benedict solution", "All of these"], answer: 0 },
  { subject: "Chemistry", question: "Distilling glycine with barium hydroxide gives:", options: ["Ethylamine", "Methylamine", "Amino acid", "Acetic acid"], answer: 1 },
  { subject: "Chemistry", question: "Which one of the following is employed as a tranquilizer drug?", options: ["Mifepristone", "Naproxen", "Valium", "Promethazine"], answer: 2 },
  { subject: "Chemistry", question: "Polymer of tetrafluoroethylene is:", options: ["PVC", "Teflon", "Dacron", "Neoprene"], answer: 1 },
  { subject: "Chemistry", question: "Which of the following is most basic in the gaseous medium?", options: ["(CH3)2NH", "(CH3)3N", "NH3", "CH3NH2"], answer: 1 },
  { subject: "Chemistry", question: "Pyroligneous acid contains:", options: ["2% acetic acid", "50% acetic acid", "10% acetic acid", "20% acetic acid"], answer: 2 }
];
